### ISSUE TITLE
Backend Has Entered The Chat

### ISSUE THREAD

**Issue by sunnybeta** [liminalminds/jdi#15]
# Tasks

- [x] Separate code into two directories: `backend` `frontend`

Create an API with Express framework:

- [ ] Sign In / Sign Up
- [ ] Save tasks of a user
- [ ] Load tasks of a user
